### ISSUE TITLE
How to compile and use the RDMA feature

### ISSUE THREAD

**Issue by junshi15** [yahoo/tensorflow#2]
We probably should put a readme in this repo as some users just want to test out rdma instead of using TensorflowOnSpark.

Here is a quick instruction.
================================
Currently, rdma is based on TF r0.12
Refer to following link for the difference
https://github.com/yahoo/tensorflow/compare/r0.12...yahoo:yahoo

### To compile:

Follow the regular TF compilation instructions. During configure step, if you want RDMA support, answer yes to this question:
    
    Do you wish to build TensorFlow with RDMA support [y/N]

Then add "**--config=rdma**" to the bazel build command.    

### To use RDMA:
In Python server definition, add the protocol:
    
    server = tf.train.Server(cluster, job_name="local", task_index=0, protocol='grpc_rdma') # default protocol is 'grpc'
    
We don't support hybrid protocols, so all the servers in the cluster have to use 'grpc_rdma'.
Now, the tensors are sent via rdma.

**Comment by AEGQ** [comment]
Thanks for your great job **: )** 

Following the steps above , I compiled a new tensorflow "with RDMA feature " , but a NotFound error is thrown while  runing the code with  protocol='grpc_rdma'. Here is what I found, and I want to confirm it is right  :


Execpt two steps as mentioned above , there should be one more additional explanations :

**_--config=rdma_** should be added while runing  **bazel build** .

**Comment by junshi15** [comment]
Yes, you are correct. I have edited the instruction above.

**Comment by AEGQ** [comment]
Thanks for your reply  , hope it can help others **: )**

**Comment by junshi15** [comment]
The updated readme file includes this information.

https://github.com/yahoo/tensorflow/blob/jun_r1.0/tensorflow/core/distributed_runtime/rdma/README.md
